version: '3.8'

services:

  billing-api:
    container_name: billing-api

    build:
      context: ./
      dockerfile: ./build/api/Dockerfile
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database

  database:
    container_name: db_postgres
    build: ./build/database
    restart: always
    volumes:
      - pgs_user_balances_volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  pgs_user_balances_volume: